<<<<<<< HEAD
title: FabZero Seppe project website
=======
title: FabZero Seppe Project website
>>>>>>> 13d46dbcab045d6148beb610d0c519726574686c
lang: en
description: FabZero van Seppe

theme: null

nav_version: true
edit: true
addons_branch: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  revision: true

readme_index:
  with_frontmatter: true

sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec
